### ISSUE TITLE
New state in the FSM for the user to inform that the payload is ok

### ISSUE THREAD

**Issue by jlrandulfe** [DronesForBlood/DronesForBlood#44]

**Comment by jlrandulfe** [comment]
Can we assume that when the user asks for a new mission the payload is already checked and ok?

**Comment by Crowdedlight** [comment]
Don't think so. But we can simulate it. So make a node called like "payload_manager" or "docking_station" that would otherwise work with docking-station operations. Then just hardcode it to output payload is alright and ready or stuff like that. As payload checking should be part of preflight, I'd say. Probably use #35 as the node. 

Could also be the one telling the drone if there is a payload or not as that changes pathplanning as stated in #43

**Comment by Gilsaa** [comment]
Maybe this can be solved by checking in the landed state? New state is unneccessary. 
Make a function called dockStatus(), which will always return true. 
If a package was onboard, call dockStatus(), then proceed to ready state.
