### ISSUE TITLE
Check irlock logs from 26/11 for unstability

### ISSUE THREAD

**Issue by Crowdedlight** [DronesForBlood/DronesForBlood#57]
The flights last monday showed some unstability when it turned around. Check logs to see if it can be seen what caused it.

**Comment by F1nsk** [comment]
Logs from our flights: 
https://review.px4.io/plot_app?log=bc5f1855-31ee-4615-9f00-5e8c736e6fa3

https://review.px4.io/plot_app?log=72f73200-4888-4810-a78a-a365334bae6d

The logs do not contain the necessary information to determine why that occurs, for instants they don't contain the all the plots that this log does https://review.px4.io/plot_app?log=26b90c8c-40fa-49de-9be4-ea2dbbe027b6 .  This might due to that we are using a custom lghging file. I have also tried to convert .tlog to  CVS files, to see if they had the necessary information. But they only contain; vehicle_local_position and irlock_report. So I suggest deleting the costume logs and doing the irlock tuning, based on how much it oscillates when doing and landing ;

> If you observe slow sideways oscillations of the vehicle while doing a precision landing with LTEST_MODE set to stationary, the beacon measurements are likely scaled too high and you should reduce the scale parameter in the relevant direction. (https://docs.px4.io/en/advanced_features/precland.html)


 So that we have the logs, which enables us to tune the whole setup.
